### PR TITLE
Add _blank target to help links in the top bar #71

### PR DESCRIPTION
**Pull request by lcoenen**
@buckwierd please review the changes. I'll push to master as soon as I have your approval.

This will fix the target of links for issue #71

### CODE REVIEW

**Comment by buckwierd** [comment]
@lcoenen I'm on staging and the help center is being opened in the same window. So it's not wortking.

**Comment by lcoenen** [comment]
@buckwierd This is not on `staging`, it's a `hotfix`

image

You have to test on your own machine or just review the code change by clicking on this 
image

**Comment by buckwierd** [comment]
Also not working on www.whichost.com

Note:
I'm seing here the comment "	lcoenen wants to merge 1 commit into master".

Am I doing something wrong? :D

**Comment by lcoenen** [comment]
You'll get used to it. 

The whole point of pull requests is to have someone to review the change *before* pushing. So here I'm asking you "hey, I did that on that branch, can I push it to master?" (as you can see above).

So in this case you have two solutions - either you load the branch on your own machine, or we set the `float` server on the branch so you can see it.

**Comment by lcoenen** [comment]
image

**Pull request merged**
