### PR TITLE
Merge staging to master on week 13

### PR DESCRIPTION
**Pull request by lcoenen**
This should fix issue #71, #88, #111, #112 and #114.

@RohrerHope @buckwierd Could you check that those issues are fixed? As soon as you confirm me, I'll merge.

### CODE REVIEW

**Comment by lcoenen** [comment]
So branch #88 isn't fixed - but it isn't broken either. 

This will have to be fixed by next launches. Issue #88 will been added to milestone week 14

**Comment by lcoenen** [comment]
Now we just need to fix issue #115 before it goes live.

**Comment by lcoenen** [comment]
@buckwierd @RohrerHope Ready when you are. Please double check one last time and I click on the big green button.

**Comment by RohrerHope** [comment]
Issue  #115 looks much better now. We are good to move forward with that fix. 👍

**Pull request merged**
